### ISSUE TITLE
Installation test fails

### ISSUE THREAD

**Issue by SamMallinson** [FloatStepper/FloatStepper#1]
On Ubuntu 18.04:

Installed OpenFOAMv2206, per https://develop.openfoam.com/Development/openfoam/blob/maintenance-v2206/doc/Build.md

Then

git clone https://github.com/FloatStepper/FloatStepper.git

cd FloatStepper

./Allwmake

No errors encountered.

./Allrun in run/circleFallingIntoWater - during first step

```code
PIMPLE: iteration 1
isoAdvection: After conservative bounding: min(alpha) = -3.46944695195e-18, max(alpha) = 1 + 0.000409588524216
Phase-1 volume fraction = 0.408948213996  Min(alpha.water) = 0  Max(alpha.water) = 1
[0]
[0]
[0] --> FOAM FATAL ERROR: (openfoam-2206)
[0] Continuity error cannot be removed by adjusting the outflow.
Please check the velocity boundary conditions and/or run potentialFoam to initialise the outflow.
Total flux              : 5425.4124404
Specified mass inflow   : 2.0115102985
Specified mass outflow  : 2.00992397114
Adjustable mass outflow : 0
```

**Comment by roenby** [comment]
Thanks for reporting!

The problem occurs in applications/floatStepper/pEqn.H in the line saying adjustPhi(phiHbyA, U, p_rgh);
adjustPhi tries to adjust the flux on all boundaries where U is of type inletOutletFvPatchVectorField such that the flow out of the domain matches the specified flow into the domain.
But before doing this, the function checks the flux balance for phiHbyA and returns a fatalError if this is above a hardcoded tolerance, as you see above. 

We essentially have

``(rho*U -rho0*U0)/deltaT + ... = -gradp + ...``

which we should match to 

``A*U = H - gradp``

giving

``HbyA ~ rho0*U0/rho.``

I don't currently see why we should require the flux of this quantity over all boundaries to equal zero. I am open to arguments here.

I have found other issues with adjustPhi, see for instance this issue:
[https://develop.openfoam.com/Development/openfoam/-/issues/1979]()

For now, I have chosen to simply outcomment adjustPhi from pEqn.H of floatStepper.

I have verified that test cases run.

Best,
Johan

**Comment by SamMallinson** [comment]
Thanks Johan @roenby - works at my end.

**Comment by roenby** [comment]
> | I have verified that test cases run.
> 
> Have you considered automated testing? Github Actions is great for this, but it requires that all requirements can be installed with a script.

That is a very good idea. Maybe to start with for testing compilation with various OpenFOAM versions, and then adding unit-like tests for the various components of the code (added mass calculators, ODE solvers, mesh motion and rewinding etc.).
